server {
    listen 80;
    
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Proxy API calls to backend container (Internal Docker Network)
    # This is optional if we use Host Nginx to split traffic, 
    # but good for container isolation.
    location /api/ {
        # Note: 'backend' is the service name in docker-compose
        proxy_pass http://backend:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
