version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile_optimized
    container_name: supply_backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - SUPPLY_ALLOWED_ORIGINS=https://YOUR_DOMAIN
      - SUPPLY_SECRET_KEY=YOUR_SECRET_KEY_HERE
      - STORAGE_TYPE=S3
      - S3_BUCKET_NAME=YOUR_S3_BUCKET_NAME
      - AWS_ACCESS_KEY_ID=YOUR_AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=YOUR_AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - ./contracts:/app/contracts
      - ./users.json:/app/users.json
      - ./backend/uploads:/app/uploads
      - ./backend/logs:/app/logs